#!/bin/bash
set -e -u -o pipefail

DEBUG=${DEBUG:-0}
dante_d=''
[[ ${DEBUG:-0} -eq 1 ]] && set -x && dante_d=" -d9"

. /etc/service/date.sh --source-only

SOURCE_DANTE_CONF=/config/dante/sockd.conf
DANTE_CONF=/etc/sockd.conf

log "########################################################"
log "INFO: DANTE: Waiting for tun0 to be up"
while [[ $(ifconfig tun0 2>&1 | grep -c "00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00") -eq 0 ]]; do
    sleep 10
done

/usr/local/bin/envsubst <${SOURCE_DANTE_CONF} >${DANTE_CONF}
log "INFO: DANTE: check configuration socks proxy"
sockd -Vf ${DANTE_CONF}
log "INFO: DANTE: set configuration socks proxy"
if [[ 0 -le $(ps -ef | grep -c sockd) ]]; then
    sockd -N 2 -f ${DANTE_CONF}
else
    pkill -9 sockd
    sockd -N 2 -f ${DANTE_CONF}
fi

sleep 5