#!/bin/bash
set -e -u -o pipefail

DEBUG=${DEBUG:-0}
[[ ${DEBUG:-0} -eq 1 ]] && set -x

. /etc/service/date.sh --source-only

log "########################################################"
if [[ -f /run/nginx/nginx.pid ]]; then
  log "INFO: nginx: stopping"
  nginx -s stop
fi